name: NAPI Build 

on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string
      target:
        required: true
        type: string
      docker:
        required: false
        type: string
      binding_dir:
        required: true
        type: string
      binding_name:
        required: true
        type: string
      npm_package_name:
        required: true
        type: string

jobs:
  build:
    name: ${{ inputs.host }} - ${{ inputs.target }} - node@20
    runs-on: ${{ inputs.host }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies
        
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: ${{ inputs.target }}-cargo-${{ inputs.host }}
          
      - name: Install rust toolchain
        if: ${{ !inputs.docker }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ inputs.target }}
          override: true
          
      - name: Enable long paths on Windows
        if: contains(inputs.host, 'windows')
        shell: bash
        run: |
          git config --system core.longpaths true
        
      - name: Build binding in docker
        uses: addnab/docker-run-action@v3
        if: ${{ inputs.docker }}
        with:
          image: ${{ inputs.docker }}
          options: |
            --user 0:0 -v ${{ github.workspace }}/.cargo-cache/git/db:/usr/local/cargo/git/db 
            -v ${{ github.workspace }}/.cargo/registry/cache:/usr/local/cargo/registry/cache 
            -v ${{ github.workspace }}/.cargo/registry/index:/usr/local/cargo/registry/index 
            -v ${{ github.workspace }}:/build 
            -w /build
          run: |
            set -e 
            rustup target add ${{ inputs.target }}
            cd ${{ inputs.binding_dir }}
            npm run build -- --target ${{ inputs.target }}
            
            
      - name: Build binding
        if: ${{ !inputs.docker }}
        shell: bash
        run: |
          # npm run build -- --target ${{ inputs.target }}
          pnpm --filter ${{ inputs.npm_package_name }} build --target ${{ inputs.target }}

      - name: Show binary
        shell: bash
        run: |
          ls -l ${{ inputs.binding_dir }}

      # - name: Build npm
      #   shell: bash
      #   run: |
      #     pnpm --filter @shined/doctor build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.binding_name }}-${{ inputs.target }}
          path: ${{ inputs.binding_dir }}/${{ inputs.binding_name }}.*.node
          if-no-files-found: error 

      - name: Upload Js
        uses: actions/upload-artifact@v4
        with:
          name: js
          path: |
            ${{ inputs.binding_dir }}/index.js
            ${{ inputs.binding_dir }}/index.d.ts
          if-no-files-found: error 
          overwrite: true
